# COLORS
MAIN_BACKGROUND_COLOR = "#282828"
FIRST_ACCENT_COLOR = "#363636"
SECOND_ACCENT_COLOR = "#1c1c1c"
FUNC_COLOR = "#A23FD8"
TEXT_COLOR = "#fff"
DISABLED_COLOR = "#999"
BORDER_COLOR = "#D428FF"

# FONT
MAIN_FONT = "Courier"

# CONSTS
PRECISION = 6